networks:
  default: null
services:
  root-spring-boot-service:
    container_name: root-spring-boot-service
    build: ./root-spring-boot-service/.
    depends_on:
    - spring-boot-service-1
    - spring-boot-service-2
    - spring-boot-service-3
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
    image: root-spring-boot-service:latest
    links:
    - spring-boot-service-1
    - spring-boot-service-2
    - spring-boot-service-3
    networks:
    - default
    ports:
    - 8080:8080
  spring-boot-service-1:
    container_name:  spring-boot-service-1
    image:
    networks:
    - default
    ports:
    - 8081:8081
  spring-boot-service-2:
    container_name: spring-boot-service-2
    image:
    networks:
    - default
    ports:
    - 8082:8082
  spring-boot-service-3:
    container_name: spring-boot-service-3
    image:
    networks:
    - default
    ports:
    - 8083:8083
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
    - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - 3000:3000
    volumes:
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/dashboards:/var/lib/grafana/dashboards/default
    links:
    - prometheus